export class CommonConstants {
  /**
   * Promotional activities.
   */
  static readonly TAB_NAME_1: string = '促销活动';

  /**
   * Trip Services.
   */
  static readonly TAB_NAME_2: string = '行程服务';

  /**
   * Promotional goods.
   */
  static readonly LIST_NAME_1: string = '促销商品';

  /**
   * Itinerary Arrangements.
   */
  static readonly LIST_NAME_2: string = '行程安排';

  /**
   * font weight is 500.
   */
  static readonly FONT_WEIGHT_FIVE: number = 500;

  /**
   * font weight is 500.
   */
  static readonly FONT_WEIGHT_FOUR: number = 400;

  /**
   * The width of the split line is 2.
   */
  static readonly STROKE_WIDTH: number = 2;

  /**
   * list space is 12.
   */
  static readonly LIST_SPACE: number = 12;

  /**
   * stack height.
   */
  static readonly STACK_HEIGHT: Length = "calc(100% - 60vp)";

  /**
   * Transparency is 1.
   */
  static readonly FULL_OPACITY: number = 1;

  /**
   * Transparency is 0.
   */
  static readonly ZERO_OPACITY: number = 0;

  /**
   * Width the percentage of the 100.
   */
  static readonly FULL_WIDTH: string = '100%';

  /**
   * Height the percentage of the 100.
   */
  static readonly FULL_HEIGHT: string = '100%';
}